#!/bin/bash

ASM_BR_PATH="assembler/browser/arc-assembler.js"
INT_BR_PATH="interpreter/browser/arc-interpreter.js"

echo "Building browser version for ARC assembler."
browserify assembler/lib/index.js -o $ASM_BR_PATH

echo "Building browser version for ARC interpreter."
browserify interpreter/lib/index.js -o $INT_BR_PATH

echo "Running minify tasks"
uglifyjs $ASM_BR_PATH -o $ASM_BR_PATH
uglifyjs $INT_BR_PATH -o $INT_BR_PATH

echo "Updating client script: arc-assembler.js"
cp $ASM_BR_PATH clients/lib/arc-assembler.js

echo "Updating client script: arc-interpreter.js"
cp $INT_BR_PATH clients/lib/arc-interpreter.js

echo "Updating gh-pages branch ..."
cp -r clients ../

echo "Checking out gh-pages branch ..."
git checkout gh-pages

echo "Updating files ..."
cp -r ../clients/* .

echo "Committing ..."
git add . -A
git commit -m "Updated browser version."

echo "Going back to the master branch."
git checkout master

echo "Cleaning up ..."
rm -rf ../clients
